version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network      
  dcs-pgadmin:
    image: dpage/pgadmin4
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 16543:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge